const auth = {
    SIGN_UP: 'SIGN_UP',
    SIGN_IN: 'SIGN_IN',
    LOG_OUT: 'LOG_OUT',
    VERIFY_USER_ACCESS: 'VERIFY_USER_ACCESS',
    VERIFY_ADMIN_ACCESS: 'VERIFY_ADMIN_ACCESS',
    CREATE_MASTER_ACCOUNT: 'CREATE_MASTER_ACCOUNT',

};

export default auth;