const auth = {
    SIGN_UP: 'SIGN_UP',
    SIGN_IN: 'SIGN_IN',
    LOG_OUT: 'LOG_OUT',
    FIND_USER_OR_CREATE: 'FIND_USER_OR_CREATE',
    VERIFY_USER_ACCESS: 'VERIFY_USER_ACCESS',
    VERIFY_ADMIN_ACCESS: 'VERIFY_ADMIN_ACCESS'
};

export default auth;