const masters = {
    GET_MASTERS: 'GET_MASTERS',
    GET_MASTER_BY_ID: 'GET_MASTER_BY_ID',
    ADD_MASTER: 'ADD_MASTER',
    UPDATE_MASTER: 'UPDATE_MASTER',
    DELETE_MASTER: 'DELETE_MASTER',
}

export default masters;