const orders = {
    GET_ORDERS: 'GET_ORDERS',
    GET_ORDER_BY_ID: 'GET_ORDER_BY_ID',
    ADD_ORDER: 'ADD_ORDER',
    UPDATE_ORDER: 'UPDATE_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    GET_CURRENT_USERS_ORDERS: 'GET_CURRENT_USERS_ORDERS',
    GET_CURRENT_MASTERS_ORDERS: 'GET_CURRENT_MASTERS_ORDERS'
};

export default orders;