const users = {
    GET_USERS: 'GET_USERS',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    RESET_PASSWORD: 'RESET_PASSWORD',
};

export default users;